{
  "formatVersion": "1.1",
  "component": {
    "url": "../../external/main-SNAPSHOT/external-main-SNAPSHOT.module",
    "group": "com.juul.indexeddb",
    "module": "external",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "external-wasm-js.klib",
          "url": "external-wasm-js-main-SNAPSHOT.klib",
          "size": 28445,
          "sha512": "27824801a5579490bb51bcc500957bf3ce24b1221a529c23c6c0f0fad8c2dc69d291a25dbe76f58c908b0a61e72fd8643cc523ef58396fb33b6f0df458c52f85",
          "sha256": "340694317b71a4504905a4aabdfe658fd7df1f2baa05928268dfbd8c2f6752b5",
          "sha1": "4ff9e30c6a45a5b7a4a3da6e61532957e6a9e006",
          "md5": "5039e309e85b45198a650b5b8548a527"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "external-wasm-js.klib",
          "url": "external-wasm-js-main-SNAPSHOT.klib",
          "size": 28445,
          "sha512": "27824801a5579490bb51bcc500957bf3ce24b1221a529c23c6c0f0fad8c2dc69d291a25dbe76f58c908b0a61e72fd8643cc523ef58396fb33b6f0df458c52f85",
          "sha256": "340694317b71a4504905a4aabdfe658fd7df1f2baa05928268dfbd8c2f6752b5",
          "sha1": "4ff9e30c6a45a5b7a4a3da6e61532957e6a9e006",
          "md5": "5039e309e85b45198a650b5b8548a527"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "external-wasm-js-sources.jar",
          "url": "external-wasm-js-main-SNAPSHOT-sources.jar",
          "size": 8757,
          "sha512": "0a88a563b0a6e2f2f9976d8e28c1a87c6e176d7ccab3e066336e76ed1f3382d9c2fc979fa138d57bafb4dd48df88cd988d3b54687bd7fe2b79c2d50a5503c0dd",
          "sha256": "c81444cbc005902f8114082330ffc5f514c8d7dd61748888d8dde08a8ec5dfa2",
          "sha1": "b8e5d0e21ea394a7b819ca9ae42c9df1d22e914a",
          "md5": "f793fd80833b5ba85a2d25fa20d88232"
        }
      ]
    }
  ]
}
