// Used via: conveyor -f conveyor.prod.conf make prod-site

// Include shared configuration
include required("conveyor.base.conf")

app {
  display-name = "Jervis Fantasy Football"
  rdns-name = "com.jervisffb"
  fsname = "jervis-fantasy-football"
}