// Used via: conveyor -f conveyor.dev.conf make site

// Include shared configuration
include required("conveyor.base.conf")

app {
  display-name = "Jervis Fantasy Football"
  rdns-name = "com.jervisffb.dev"
  fsname = "jervis-fantasy-football-dev"
}