{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juul.indexeddb",
    "module": "logging-khronicle",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "core",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "com.juul.khronicle",
          "module": "khronicle-core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "logging-khronicle-metadata.jar",
          "url": "logging-khronicle-main-SNAPSHOT.jar",
          "size": 2664,
          "sha512": "16102318a10bf25a61d25f2d31956f39c470f89682d7ac348768fb56b117c44fdedf16a464cf7a6249258d174ea5ce1c167d7eedf4be7c9a2d05f757c8caed49",
          "sha256": "cb99462c0f1f747d41545b548236f4c1cd583a6f7ae99369d2e8961849be336b",
          "sha1": "6ed70a063a12247920ab75930ccfc8b951b228d6",
          "md5": "14ed7b8f05a97735239165533a1109b0"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "logging-khronicle-kotlin-sources.jar",
          "url": "logging-khronicle-main-SNAPSHOT-sources.jar",
          "size": 1041,
          "sha512": "cd73e3352680b85bf4a1d2ed727f688c6a1643825293b3db227d339f5e00b3027fc0274d6d083b895e65e4b9e73aa673e031c4905677412bd479a9f69a5de9e6",
          "sha256": "15ec39deb2ebaf84ffcafb1b0abd1104a30513caa936923956d67087067f3397",
          "sha1": "4e3c5ebdb12c8290359b772b19724049819c54ad",
          "md5": "ee44c2e3956f376fb49ea3303ed4094b"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-js/main-SNAPSHOT/logging-khronicle-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-js/main-SNAPSHOT/logging-khronicle-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-js/main-SNAPSHOT/logging-khronicle-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-wasm-js/main-SNAPSHOT/logging-khronicle-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-wasm-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-wasm-js/main-SNAPSHOT/logging-khronicle-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-wasm-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../logging-khronicle-wasm-js/main-SNAPSHOT/logging-khronicle-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "logging-khronicle-wasm-js",
        "version": "main-SNAPSHOT"
      }
    }
  ]
}
