{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/main-SNAPSHOT/core-main-SNAPSHOT.module",
    "group": "com.juul.indexeddb",
    "module": "core",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "external",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "core-js-main-SNAPSHOT.klib",
          "size": 69271,
          "sha512": "599540f12c7579bfa5d6b17244c3bd1b4de1b4841c10162e1d8b60a5ce76b1e44ace3ef1c90a9b946440b870fa555cfe97078e9275ff98c174cb63840fc4cd9a",
          "sha256": "17ed1beedb4bdffe51695a3bcc12d27455d2a275886ef54ed6924758eb1af71f",
          "sha1": "6f77ce5296fba16921595c2903832ec9846885d3",
          "md5": "d5e1accb863003e5e2c9f7fea3f08164"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "external",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-js.klib",
          "url": "core-js-main-SNAPSHOT.klib",
          "size": 69271,
          "sha512": "599540f12c7579bfa5d6b17244c3bd1b4de1b4841c10162e1d8b60a5ce76b1e44ace3ef1c90a9b946440b870fa555cfe97078e9275ff98c174cb63840fc4cd9a",
          "sha256": "17ed1beedb4bdffe51695a3bcc12d27455d2a275886ef54ed6924758eb1af71f",
          "sha1": "6f77ce5296fba16921595c2903832ec9846885d3",
          "md5": "d5e1accb863003e5e2c9f7fea3f08164"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "core-js-sources.jar",
          "url": "core-js-main-SNAPSHOT-sources.jar",
          "size": 13113,
          "sha512": "ce66b6abd15ddb90fcbb7bed1676dac10bd3ecc9b5b4e853b377d8388891b125746f2d876b4eee6d1e91debd5a97bca3c6d77f619331bb65965d9af0b4b439bb",
          "sha256": "5f6bd9a76f238028b4fe3a8bfca547f8e1eae041454826c3633ce1c5991d37a8",
          "sha1": "3460301f8bc28fb3b93664098e8e1a93622bec57",
          "md5": "dcde881861eafb6cd791990ad5ce00b2"
        }
      ]
    }
  ]
}
