package com.jervisffb.engine.serialize

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 */
val generatedJervisSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.model.inducements.BiasedReferee::class) {
        subclass(com.jervisffb.engine.model.inducements.StandardBiasedReferee::class)
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.procedures.DieRoll::class) {
        subclass(com.jervisffb.engine.rules.bb2020.procedures.BlockDieRoll::class)
        subclass(com.jervisffb.engine.rules.bb2020.procedures.D6DieRoll::class)
    }
    polymorphic(com.jervisffb.engine.actions.GameAction::class) {
        subclass(com.jervisffb.engine.actions.BlockTypeSelected::class)
        subclass(com.jervisffb.engine.actions.Cancel::class)
        subclass(com.jervisffb.engine.actions.CoinSideSelected::class)
        subclass(com.jervisffb.engine.actions.CoinTossResult::class)
        subclass(com.jervisffb.engine.actions.CompositeGameAction::class)
        subclass(com.jervisffb.engine.actions.Confirm::class)
        subclass(com.jervisffb.engine.actions.Continue::class)
        subclass(com.jervisffb.engine.actions.D12Result::class)
        subclass(com.jervisffb.engine.actions.D16Result::class)
        subclass(com.jervisffb.engine.actions.D20Result::class)
        subclass(com.jervisffb.engine.actions.D2Result::class)
        subclass(com.jervisffb.engine.actions.D3Result::class)
        subclass(com.jervisffb.engine.actions.D4Result::class)
        subclass(com.jervisffb.engine.actions.D6Result::class)
        subclass(com.jervisffb.engine.actions.D8Result::class)
        subclass(com.jervisffb.engine.actions.DBlockResult::class)
        subclass(com.jervisffb.engine.actions.DicePoolResultsSelected::class)
        subclass(com.jervisffb.engine.actions.DiceRollResults::class)
        subclass(com.jervisffb.engine.actions.DirectionSelected::class)
        subclass(com.jervisffb.engine.actions.DogoutSelected::class)
        subclass(com.jervisffb.engine.actions.EndAction::class)
        subclass(com.jervisffb.engine.actions.EndSetup::class)
        subclass(com.jervisffb.engine.actions.EndTurn::class)
        subclass(com.jervisffb.engine.actions.FieldSquareSelected::class)
        subclass(com.jervisffb.engine.actions.InducementSelected::class)
        subclass(com.jervisffb.engine.actions.MoveTypeSelected::class)
        subclass(com.jervisffb.engine.actions.NoRerollSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerActionSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerDeselected::class)
        subclass(com.jervisffb.engine.actions.PlayerSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerSubActionSelected::class)
        subclass(com.jervisffb.engine.actions.RandomPlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RerollOptionSelected::class)
        subclass(com.jervisffb.engine.actions.Revert::class)
        subclass(com.jervisffb.engine.actions.SkillSelected::class)
        subclass(com.jervisffb.engine.actions.Undo::class)
        polymorphic(com.jervisffb.engine.actions.DieResult::class) {
            subclass(com.jervisffb.engine.actions.D12Result::class)
            subclass(com.jervisffb.engine.actions.D16Result::class)
            subclass(com.jervisffb.engine.actions.D20Result::class)
            subclass(com.jervisffb.engine.actions.D2Result::class)
            subclass(com.jervisffb.engine.actions.D3Result::class)
            subclass(com.jervisffb.engine.actions.D4Result::class)
            subclass(com.jervisffb.engine.actions.D6Result::class)
            subclass(com.jervisffb.engine.actions.D8Result::class)
            subclass(com.jervisffb.engine.actions.DBlockResult::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.locations.Location::class) {
        subclass(com.jervisffb.engine.model.FieldSquare::class)
        subclass(com.jervisffb.engine.model.locations.DogOut::class)
        subclass(com.jervisffb.engine.model.locations.FieldCoordinateImpl::class)
        subclass(com.jervisffb.engine.model.locations.GiantLocation::class)
        polymorphic(com.jervisffb.engine.model.locations.FieldCoordinate::class) {
            subclass(com.jervisffb.engine.model.FieldSquare::class)
            subclass(com.jervisffb.engine.model.locations.FieldCoordinateImpl::class)
        }
        polymorphic(com.jervisffb.engine.model.locations.OnFieldLocation::class) {
            subclass(com.jervisffb.engine.model.FieldSquare::class)
            subclass(com.jervisffb.engine.model.locations.FieldCoordinateImpl::class)
            subclass(com.jervisffb.engine.model.locations.GiantLocation::class)
            polymorphic(com.jervisffb.engine.model.locations.FieldCoordinate::class) {
                subclass(com.jervisffb.engine.model.FieldSquare::class)
                subclass(com.jervisffb.engine.model.locations.FieldCoordinateImpl::class)
            }
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.rules.common.pathfinder.BB2020PathFinder::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Position::class) {
        subclass(com.jervisffb.engine.rules.bb2020.roster.BB2020Position::class)
        subclass(com.jervisffb.engine.rules.bb2020.roster.BB2020StarPlayer::class)
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.skills.RerollSource::class) {
        subclass(com.jervisffb.engine.rules.bb2020.skills.BrilliantCoachingReroll::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.LeaderTeamReroll::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Pro::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.RegularTeamReroll::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands::class)
        polymorphic(com.jervisffb.engine.rules.bb2020.skills.D6StandardSkillReroll::class) {
            subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands::class)
        }
        polymorphic(com.jervisffb.engine.rules.bb2020.skills.TeamReroll::class) {
            subclass(com.jervisffb.engine.rules.bb2020.skills.BrilliantCoachingReroll::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.LeaderTeamReroll::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.RegularTeamReroll::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Roster::class) {
        subclass(com.jervisffb.engine.rules.bb2020.roster.BB2020Roster::class)
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
        subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        polymorphic(com.jervisffb.engine.rules.BB2020Rules::class) {
            subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
            subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.skills.Skill::class) {
        subclass(com.jervisffb.engine.rules.bb2020.skills.AnimalSavagery::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Block::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BloodLust::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BoneHead::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BreakTackle::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BreatheFire::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.DivingTackle::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Frenzy::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Horns::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Leap::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Loner::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.MightyBlow::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.MultipleBlock::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Pass::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.PrehensileTail::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Pro::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ProjectileVomit::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ReallyStupid::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Regeneration::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Sidestep::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Sprint::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Stab::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Stunty::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Tackle::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ThickSkull::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Timmmber::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Titchy::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.TwoHeads::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.UnchannelledFury::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Wrestle::class)
        subclass(com.jervisffb.engine.rules.bb2020.specialrules.SneakiestOfTheLot::class)
        polymorphic(com.jervisffb.engine.rules.bb2020.skills.BB2020Skill::class) {
            subclass(com.jervisffb.engine.rules.bb2020.skills.AnimalSavagery::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Block::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BloodLust::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BoneHead::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BreakTackle::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BreatheFire::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.DivingTackle::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Frenzy::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Horns::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Leap::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Loner::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.MightyBlow::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.MultipleBlock::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Pass::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.PrehensileTail::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Pro::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ProjectileVomit::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ReallyStupid::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Regeneration::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Sidestep::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Sprint::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Stab::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Stunty::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Tackle::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ThickSkull::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Timmmber::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Titchy::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.TwoHeads::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.UnchannelledFury::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Wrestle::class)
        }
        polymorphic(com.jervisffb.engine.rules.bb2020.specialrules.BB2020SpecialRule::class) {
            subclass(com.jervisffb.engine.rules.bb2020.specialrules.SneakiestOfTheLot::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.skills.SkillFactory::class) {
        subclass(com.jervisffb.engine.rules.bb2020.skills.AnimalSavagery.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Block.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BloodLust.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BoneHead.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BreakTackle.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.BreatheFire.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.DivingTackle.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Frenzy.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Horns.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Leap.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Loner.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.MightyBlow.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.MultipleBlock.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Pass.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.PrehensileTail.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Pro.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ProjectileVomit.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ReallyStupid.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Regeneration.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Sidestep.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Sprint.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Stab.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Stunty.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Tackle.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.ThickSkull.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Timmmber.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Titchy.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.TwoHeads.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.UnchannelledFury.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.skills.Wrestle.Factory::class)
        subclass(com.jervisffb.engine.rules.bb2020.specialrules.SneakiestOfTheLot.Factory::class)
        polymorphic(com.jervisffb.engine.rules.bb2020.skills.PlayerSkillFactory::class) {
            subclass(com.jervisffb.engine.rules.bb2020.skills.AnimalSavagery.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Block.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BloodLust.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BoneHead.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BreakTackle.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.BreatheFire.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.CatchSkill.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.DivingTackle.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Dodge.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Frenzy.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Horns.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Leap.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Loner.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.MightyBlow.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.MultipleBlock.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Pass.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.PrehensileTail.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Pro.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ProjectileVomit.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ReallyStupid.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Regeneration.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Sidestep.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Sprint.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Stab.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Stunty.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureFeet.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.SureHands.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Tackle.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.ThickSkull.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Timmmber.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Titchy.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.TwoHeads.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.UnchannelledFury.Factory::class)
            subclass(com.jervisffb.engine.rules.bb2020.skills.Wrestle.Factory::class)
        }
        polymorphic(com.jervisffb.engine.rules.bb2020.specialrules.SpecialRuleFactory::class) {
            subclass(com.jervisffb.engine.rules.bb2020.specialrules.SneakiestOfTheLot.Factory::class)
        }
    }
    polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.model.inducements.wizards.Zap::class)
    }
    polymorphic(com.jervisffb.engine.rules.TeamActions::class) {
        subclass(com.jervisffb.engine.rules.BB2020TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.HirelingSportsWizard::class)
    }
}
