package com.jervisffb.engine.serialize

import com.jervisffb.engine.rules.bb2020.BB2020TeamActions
import com.jervisffb.engine.rules.common.actions.TeamActions
import com.jervisffb.engine.rules.common.roster.RosterPosition
import com.jervisffb.engine.rules.common.roster.StarPlayerPosition
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 */
val generatedJervisSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.model.inducements.BiasedReferee::class) {
        subclass(com.jervisffb.engine.model.inducements.StandardBiasedReferee::class)
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.procedures.DieRoll::class) {
        subclass(com.jervisffb.engine.rules.bb2020.procedures.BlockDieRoll::class)
        subclass(com.jervisffb.engine.rules.bb2020.procedures.D6DieRoll::class)
    }
    polymorphic(com.jervisffb.engine.actions.GameAction::class) {
        subclass(com.jervisffb.engine.actions.BlockTypeSelected::class)
        subclass(com.jervisffb.engine.actions.Cancel::class)
        subclass(com.jervisffb.engine.actions.CoinSideSelected::class)
        subclass(com.jervisffb.engine.actions.CoinTossResult::class)
        subclass(com.jervisffb.engine.actions.CompositeGameAction::class)
        subclass(com.jervisffb.engine.actions.Confirm::class)
        subclass(com.jervisffb.engine.actions.Continue::class)
        subclass(com.jervisffb.engine.actions.D12Result::class)
        subclass(com.jervisffb.engine.actions.D16Result::class)
        subclass(com.jervisffb.engine.actions.D20Result::class)
        subclass(com.jervisffb.engine.actions.D2Result::class)
        subclass(com.jervisffb.engine.actions.D3Result::class)
        subclass(com.jervisffb.engine.actions.D4Result::class)
        subclass(com.jervisffb.engine.actions.D6Result::class)
        subclass(com.jervisffb.engine.actions.D8Result::class)
        subclass(com.jervisffb.engine.actions.DBlockResult::class)
        subclass(com.jervisffb.engine.actions.DicePoolResultsSelected::class)
        subclass(com.jervisffb.engine.actions.DiceRollResults::class)
        subclass(com.jervisffb.engine.actions.DirectionSelected::class)
        subclass(com.jervisffb.engine.actions.DogoutSelected::class)
        subclass(com.jervisffb.engine.actions.EndAction::class)
        subclass(com.jervisffb.engine.actions.EndSetup::class)
        subclass(com.jervisffb.engine.actions.EndTurn::class)
        subclass(com.jervisffb.engine.actions.FieldSquareSelected::class)
        subclass(com.jervisffb.engine.actions.InducementSelected::class)
        subclass(com.jervisffb.engine.actions.MoveTypeSelected::class)
        subclass(com.jervisffb.engine.actions.NoRerollSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerActionSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerDeselected::class)
        subclass(com.jervisffb.engine.actions.PlayerSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerSubActionSelected::class)
        subclass(com.jervisffb.engine.actions.RandomPlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RerollOptionSelected::class)
        subclass(com.jervisffb.engine.actions.Revert::class)
        subclass(com.jervisffb.engine.actions.SkillSelected::class)
        subclass(com.jervisffb.engine.actions.Undo::class)
        polymorphic(com.jervisffb.engine.actions.DieResult::class) {
            subclass(com.jervisffb.engine.actions.D12Result::class)
            subclass(com.jervisffb.engine.actions.D16Result::class)
            subclass(com.jervisffb.engine.actions.D20Result::class)
            subclass(com.jervisffb.engine.actions.D2Result::class)
            subclass(com.jervisffb.engine.actions.D3Result::class)
            subclass(com.jervisffb.engine.actions.D4Result::class)
            subclass(com.jervisffb.engine.actions.D6Result::class)
            subclass(com.jervisffb.engine.actions.D8Result::class)
            subclass(com.jervisffb.engine.actions.DBlockResult::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7KickOffEventTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.StandardKickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.rules.common.pathfinder.BB2020PathFinder::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Position::class) {
        subclass(RosterPosition::class)
        subclass(StarPlayerPosition::class)
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7PrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.StandardPrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Roster::class) {
        subclass(com.jervisffb.engine.rules.bb2020.roster.BB2020Roster::class)
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.rules.BB72020Rules::class)
        subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
        subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        polymorphic(com.jervisffb.engine.rules.BB2020Rules::class) {
            subclass(com.jervisffb.engine.rules.BB72020Rules::class)
            subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
            subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        }
    }
    polymorphic(com.jervisffb.engine.serialize.SerializedPlayer::class) {
    }
    polymorphic(com.jervisffb.engine.serialize.SerializedTeam::class) {
    }
    polymorphic(com.jervisffb.engine.rules.bb2020.SkillSettings::class) {
        subclass(com.jervisffb.engine.rules.bb2020.BB2020SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.model.inducements.wizards.Zap::class)
    }
    polymorphic(TeamActions::class) {
        subclass(BB2020TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.HirelingSportsWizard::class)
    }
}
