package com.jervisffb.engine.serialize

import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

/**
 * WARNING: This file is autogenerated. Do not modify manully
 * Instead rerun the notebook in `tools/GenerateSerializers.ipynb` to update.
 */
val generatedJervisSerializerModule = SerializersModule {
    polymorphic(com.jervisffb.engine.rules.common.tables.ArgueTheCallTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020ArgueTheCallTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025ArgueTheCallTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.builder.BallSelectorRule::class) {
        subclass(com.jervisffb.engine.rules.builder.RollOnUnusualBallTable::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificUnusualBall::class)
        subclass(com.jervisffb.engine.rules.builder.StandardBall::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.BiasedReferee::class) {
        subclass(com.jervisffb.engine.model.inducements.StandardBiasedReferee::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.CasualtyTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020CasualtyTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025CasualtyTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.procedures.DieRoll::class) {
        subclass(com.jervisffb.engine.rules.common.procedures.BlockDieRoll::class)
        subclass(com.jervisffb.engine.rules.common.procedures.D6DieRoll::class)
    }
    polymorphic(com.jervisffb.engine.actions.GameAction::class) {
        subclass(com.jervisffb.engine.actions.BlockTypeSelected::class)
        subclass(com.jervisffb.engine.actions.Cancel::class)
        subclass(com.jervisffb.engine.actions.CoinSideSelected::class)
        subclass(com.jervisffb.engine.actions.CoinTossResult::class)
        subclass(com.jervisffb.engine.actions.CompositeGameAction::class)
        subclass(com.jervisffb.engine.actions.Confirm::class)
        subclass(com.jervisffb.engine.actions.Continue::class)
        subclass(com.jervisffb.engine.actions.D12Result::class)
        subclass(com.jervisffb.engine.actions.D16Result::class)
        subclass(com.jervisffb.engine.actions.D20Result::class)
        subclass(com.jervisffb.engine.actions.D2Result::class)
        subclass(com.jervisffb.engine.actions.D3Result::class)
        subclass(com.jervisffb.engine.actions.D4Result::class)
        subclass(com.jervisffb.engine.actions.D6Result::class)
        subclass(com.jervisffb.engine.actions.D8Result::class)
        subclass(com.jervisffb.engine.actions.DBlockResult::class)
        subclass(com.jervisffb.engine.actions.DicePoolResultsSelected::class)
        subclass(com.jervisffb.engine.actions.DiceRollResults::class)
        subclass(com.jervisffb.engine.actions.DirectionSelected::class)
        subclass(com.jervisffb.engine.actions.DogoutSelected::class)
        subclass(com.jervisffb.engine.actions.EndAction::class)
        subclass(com.jervisffb.engine.actions.EndSetup::class)
        subclass(com.jervisffb.engine.actions.EndTurn::class)
        subclass(com.jervisffb.engine.actions.FieldSquareSelected::class)
        subclass(com.jervisffb.engine.actions.InducementSelected::class)
        subclass(com.jervisffb.engine.actions.MoveTypeSelected::class)
        subclass(com.jervisffb.engine.actions.NoRerollSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerActionSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerDeselected::class)
        subclass(com.jervisffb.engine.actions.PlayerSelected::class)
        subclass(com.jervisffb.engine.actions.PlayerSubActionSelected::class)
        subclass(com.jervisffb.engine.actions.RandomPlayersSelected::class)
        subclass(com.jervisffb.engine.actions.RerollOptionSelected::class)
        subclass(com.jervisffb.engine.actions.Revert::class)
        subclass(com.jervisffb.engine.actions.SkillSelected::class)
        subclass(com.jervisffb.engine.actions.Undo::class)
        polymorphic(com.jervisffb.engine.actions.DieResult::class) {
            subclass(com.jervisffb.engine.actions.D12Result::class)
            subclass(com.jervisffb.engine.actions.D16Result::class)
            subclass(com.jervisffb.engine.actions.D20Result::class)
            subclass(com.jervisffb.engine.actions.D2Result::class)
            subclass(com.jervisffb.engine.actions.D3Result::class)
            subclass(com.jervisffb.engine.actions.D4Result::class)
            subclass(com.jervisffb.engine.actions.D6Result::class)
            subclass(com.jervisffb.engine.actions.D8Result::class)
            subclass(com.jervisffb.engine.actions.DBlockResult::class)
        }
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.InjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7StuntyInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StuntyInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.KickOffTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardKickOffEventTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7KickOffEventTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardKickOffEventTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.LastingInjuryTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020LastingInjuryTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025LastingInjuryTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.pathfinder.PathFinder::class) {
        subclass(com.jervisffb.engine.rules.common.pathfinder.BB2020PathFinder::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Position::class) {
        subclass(com.jervisffb.engine.rules.common.roster.RosterPosition::class)
        subclass(com.jervisffb.engine.rules.common.roster.StarPlayerPosition::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.PrayersToNuffleTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardPrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB7PrayersToNuffleTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardPrayersToNuffleTable::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.RangeRuler::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020RangeRuler::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025RangeRuler::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.roster.Roster::class) {
        subclass(com.jervisffb.engine.rules.bb2020.roster.BB2020Roster::class)
    }
    polymorphic(com.jervisffb.engine.rules.Rules::class) {
        subclass(com.jervisffb.engine.rules.BB72020Rules::class)
        subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
        subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        subclass(com.jervisffb.engine.rules.StandardBB2025Rules::class)
        polymorphic(com.jervisffb.engine.rules.BB2020Rules::class) {
            subclass(com.jervisffb.engine.rules.BB72020Rules::class)
            subclass(com.jervisffb.engine.rules.FumbblBB2020Rules::class)
            subclass(com.jervisffb.engine.rules.StandardBB2020Rules::class)
        }
        polymorphic(com.jervisffb.engine.rules.BB2025Rules::class) {
            subclass(com.jervisffb.engine.rules.StandardBB2025Rules::class)
        }
    }
    polymorphic(com.jervisffb.engine.serialize.SerializedPlayer::class) {
    }
    polymorphic(com.jervisffb.engine.serialize.SerializedTeam::class) {
    }
    polymorphic(com.jervisffb.engine.rules.common.skills.SkillSettings::class) {
        subclass(com.jervisffb.engine.rules.bb2020.BB2020SkillSettings::class)
    }
    polymorphic(com.jervisffb.engine.rules.builder.StadiumRule::class) {
        subclass(com.jervisffb.engine.rules.builder.NoStadium::class)
        subclass(com.jervisffb.engine.rules.builder.RollForStadiumUsed::class)
        subclass(com.jervisffb.engine.rules.builder.SpecificStadium::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.Spell::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.Fireball::class)
        subclass(com.jervisffb.engine.model.inducements.wizards.Zap::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.actions.TeamActions::class) {
        subclass(com.jervisffb.engine.rules.bb2020.BB2020TeamActions::class)
        subclass(com.jervisffb.engine.rules.bb2025.BB2025TeamActions::class)
    }
    polymorphic(com.jervisffb.engine.rules.common.tables.WeatherTable::class) {
        subclass(com.jervisffb.engine.rules.bb2020.tables.AutumnWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.BB2020StandardWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.SpringWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.SummerWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2020.tables.WinterWeatherTable::class)
        subclass(com.jervisffb.engine.rules.bb2025.tables.BB2025StandardWeatherTable::class)
    }
    polymorphic(com.jervisffb.engine.model.inducements.wizards.Wizard::class) {
        subclass(com.jervisffb.engine.model.inducements.wizards.HirelingSportsWizard::class)
    }
}
