package com.jervisffb.engine.rules

/**
 * Enumerate all dice roll types available across all variants of Blood Bowl.
 */
enum class DiceRollType(val description: String) {
    ACCURACY("Accuracy"), // For passing and Throw Teammate (in BB2025)
    ANIMAL_SAVAGERY("Animal Savagery"),
    ARGUE_THE_CALL("Argue the Call"),
    ARMOUR("Armour"),
    BAD_HABITS("Bad Habits"),
    BB7_APOTHECARY("Apothecary"),
    BLOCK("Block"),
    BLITZ("Blitz"),
    BLOODLUST("Bloodlust"),
    BONE_HEAD("Bone Head"),
    BOUNCE("Bounce"),
    BRIBE("Bribe"),
    BREATHE_FIRE("Breathe Fire"),
    BRILLIANT_COACHING("Brilliant Coaching"),
    CASUALTY("Casualty"),
    CATCH("Catch"),
    CHAINSAW("Chainsaw"),
    CHARGE("Charge"),
    CHEERING_FANS("Cheering Fans"),
    CHOMP("Chomp"),
    CROWD_TAKES_ACTION("Crowd Takes Action"), // Stalling
    FAN_FACTOR("Fan Factor"),
    FOUL_APPEARANCE("Foul Appearance"),
    DAUNTLESS("Dauntless"),
    DODGE("Dodge"),
    DODGY_SNACK_ROLL_OFF("Dodgy Snack"),
    DODGY_SNACK_EFFECT("Dodgy Snack"),
    DEVIATE("Deviate"),
    HYPNOTIC_GAZE("Hypnotic Gaze"),
    INJURY("Injury"),
    INTERCEPTION("Interception"), // Only used in BB2025
    JUMP("Jump"),
    JUMP_UP("Jump Up"),
    KICK_OFF_TABLE("Kick Off"),
    LANDING("Landing"),
    LASTING_INJURY("Lasting Injury"),
    LEAP("Leap"),
    LONER("Loner"),
    OFFICIOUS_REF_FAN_FACTOR("Officious Ref"),
    OFFICIOUS_REF_REFEREE("Officious Ref"),
    PASS("Pass"),
    PASSING_INTERFERENCE("Passing Interference"), // Only used in BB2020
    PICKUP("Pickup"),
    PITCH_INVASION_FAN_FACTOR("Pitch Invasion"),
    PITCH_INVASION_PLAYERS_AFFECTED("Pitch Invasion"),
    POGO("Pogo"),
    PRO("Pro"),
    PRAYERS_TO_NUFFLE("Prayers To Nuffle"),
    REALLY_STUPID("Really Stupid"),
    REGENERATION("Regeneration"),
    QUALITY("Quality"),
    QUICK_SNAP("Quick Snap"),
    RECOVER_PLAYER("Recover Player"),
    RUSH("Rush"),
    SCATTER("Scatter"),
    SECURE_THE_BALL("Secure The Ball"),
    SHADOWING("Shadowing"),
    SOLID_DEFENSE("Solid Defense"),
    SUDDEN_DEATH("Sudden Death"),
    STANDING_UP("Standing Up"),
    STEADY_FOOTING("Steady Footing"),
    SWELTERING_HEAT("Sweltering Heat"),
    SWOOP_DIRECTION("Swoop Direction"),
    SWOOP_DISTANCE("Swoop Distance"),
    TAKE_ROOT("Take Root"),
    TEAM_CAPTAIN("Team Captain"),
    TEAM_MASCOT("Team Mascot"),
    TENTACLES("Tentacles"),
    THROW_A_ROCK("Throw A Rock"),
    THROWIN_DIRECTION("Throw-in Direction"),
    THROWIN_DISTANCE("Throw-in Distance"),
    TREACHEROUS_TRAPDOOR("Treacherous Trapdoor"),
    UNCHANNELLED_FURY("Unchannelled Fury"),
    PROJECTILE_VOMIT("Projectile Vomit"),
    PUNT_DIRECTION("Punt Direction"),
    PUNT_DISTANCE("Punt Distance"),
    WEATHER("Weather"),
}
