{
  "formatVersion": "1.1",
  "component": {
    "url": "../../external/main-SNAPSHOT/external-main-SNAPSHOT.module",
    "group": "com.juul.indexeddb",
    "module": "external",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "external-js.klib",
          "url": "external-js-main-SNAPSHOT.klib",
          "size": 28455,
          "sha512": "1958f927c85103f93adee8c6eae50a2be1964928e57b55140881eb939c310d3a06fd3f8ce852406168ff2fa376bff7005b383a62d81b4f0c51070c4d43ce4ca6",
          "sha256": "0a7736c26cc62aef839b7775c8b4232b6847d071ae4e705a413ce6f9c571b135",
          "sha1": "d2241076f6e59f5ea0b1ce463e5fc5bf2b2ba212",
          "md5": "3bf7d44e7030426f02496cddc8d34ab7"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-dom-api-compat",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "external-js.klib",
          "url": "external-js-main-SNAPSHOT.klib",
          "size": 28455,
          "sha512": "1958f927c85103f93adee8c6eae50a2be1964928e57b55140881eb939c310d3a06fd3f8ce852406168ff2fa376bff7005b383a62d81b4f0c51070c4d43ce4ca6",
          "sha256": "0a7736c26cc62aef839b7775c8b4232b6847d071ae4e705a413ce6f9c571b135",
          "sha1": "d2241076f6e59f5ea0b1ce463e5fc5bf2b2ba212",
          "md5": "3bf7d44e7030426f02496cddc8d34ab7"
        }
      ]
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "external-js-sources.jar",
          "url": "external-js-main-SNAPSHOT-sources.jar",
          "size": 8757,
          "sha512": "0a88a563b0a6e2f2f9976d8e28c1a87c6e176d7ccab3e066336e76ed1f3382d9c2fc979fa138d57bafb4dd48df88cd988d3b54687bd7fe2b79c2d50a5503c0dd",
          "sha256": "c81444cbc005902f8114082330ffc5f514c8d7dd61748888d8dde08a8ec5dfa2",
          "sha1": "b8e5d0e21ea394a7b819ca9ae42c9df1d22e914a",
          "md5": "f793fd80833b5ba85a2d25fa20d88232"
        }
      ]
    }
  ]
}
