{
  "formatVersion": "1.1",
  "component": {
    "url": "../../core/main-SNAPSHOT/core-main-SNAPSHOT.module",
    "group": "com.juul.indexeddb",
    "module": "core",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "external",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-wasm-js.klib",
          "url": "core-wasm-js-main-SNAPSHOT.klib",
          "size": 69730,
          "sha512": "9351dadd08f5cc27dc70ad80129e5ee1fcc507306a6235d605f5875d85a79a5778e0a640bc219aee56fcc488a1eeb957c8f93296da10bae32fc55e72c3a4b36b",
          "sha256": "3999d9bea24e8bfb5527b5d33be211ef7037ddffee829e2229ee4811b6319549",
          "sha1": "39f6be5b2e49bf86d5580fe0d919e573a4458125",
          "md5": "80d011453bce491ab4465ef29cb8efbc"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "external",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-wasm-js.klib",
          "url": "core-wasm-js-main-SNAPSHOT.klib",
          "size": 69730,
          "sha512": "9351dadd08f5cc27dc70ad80129e5ee1fcc507306a6235d605f5875d85a79a5778e0a640bc219aee56fcc488a1eeb957c8f93296da10bae32fc55e72c3a4b36b",
          "sha256": "3999d9bea24e8bfb5527b5d33be211ef7037ddffee829e2229ee4811b6319549",
          "sha1": "39f6be5b2e49bf86d5580fe0d919e573a4458125",
          "md5": "80d011453bce491ab4465ef29cb8efbc"
        }
      ]
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "files": [
        {
          "name": "core-wasm-js-sources.jar",
          "url": "core-wasm-js-main-SNAPSHOT-sources.jar",
          "size": 13113,
          "sha512": "ce66b6abd15ddb90fcbb7bed1676dac10bd3ecc9b5b4e853b377d8388891b125746f2d876b4eee6d1e91debd5a97bca3c6d77f619331bb65965d9af0b4b439bb",
          "sha256": "5f6bd9a76f238028b4fe3a8bfca547f8e1eae041454826c3633ce1c5991d37a8",
          "sha1": "3460301f8bc28fb3b93664098e8e1a93622bec57",
          "md5": "dcde881861eafb6cd791990ad5ce00b2"
        }
      ]
    }
  ]
}
