{
  "formatVersion": "1.1",
  "component": {
    "group": "com.juul.indexeddb",
    "module": "core",
    "version": "main-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "com.juul.indexeddb",
          "module": "external",
          "version": {
            "requires": "main-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "core-metadata.jar",
          "url": "core-main-SNAPSHOT.jar",
          "size": 15130,
          "sha512": "bd3ea6eb8d75723f177220e28987d25b7e544db31f6c81ae659e2987a43b087a8084b63a855b88c3174cd511f6c74138fdd20e12354bd8b1905a468e28caa9f2",
          "sha256": "76771138f790d38e7f4f98da38fb64f554b9a91d449159689d9c99c0ad6eadfc",
          "sha1": "b0d4849ddf14762984c5ae58992c7f781e33fd0c",
          "md5": "f91d98afb8b6749398082b7255d724a5"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "core-kotlin-sources.jar",
          "url": "core-main-SNAPSHOT-sources.jar",
          "size": 13113,
          "sha512": "ce66b6abd15ddb90fcbb7bed1676dac10bd3ecc9b5b4e853b377d8388891b125746f2d876b4eee6d1e91debd5a97bca3c6d77f619331bb65965d9af0b4b439bb",
          "sha256": "5f6bd9a76f238028b4fe3a8bfca547f8e1eae041454826c3633ce1c5991d37a8",
          "sha1": "3460301f8bc28fb3b93664098e8e1a93622bec57",
          "md5": "dcde881861eafb6cd791990ad5ce00b2"
        }
      ]
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/main-SNAPSHOT/core-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/main-SNAPSHOT/core-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../core-js/main-SNAPSHOT/core-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-wasm-js/main-SNAPSHOT/core-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-wasm-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-wasm-js/main-SNAPSHOT/core-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-wasm-js",
        "version": "main-SNAPSHOT"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../core-wasm-js/main-SNAPSHOT/core-wasm-js-main-SNAPSHOT.module",
        "group": "com.juul.indexeddb",
        "module": "core-wasm-js",
        "version": "main-SNAPSHOT"
      }
    }
  ]
}
