# These settings will be applied when the Client is initialized
# TODO Figure out how to handle client version updates and new settings are applied

# FUMBBL values
fumbbl.oauth.token=
fumbbl.client.name=
fumbbl.client.id=
fumbbl.client.secret=

# Settings to save between creating new Standalone games
jervis.default.client.coach.name=
jervis.default.host.coach.name=

# The following sections follow a certain format in order to auto-generate code
# that can be used to generate the in-game menu. Each section must start with
# a special directive entry: <xx>.<yy>.label=<header>.
# This will generate a top-level menu which will contain all entries with the
# same <xx>.<yy> prefix.
# Only boolean values are supported right now.

# -- GAME_MENU: Automatic Actions --
# Actions that will automatically be selected by the Game Client before the
# Coach is presented with the option
jervis.autoAction.sectionLabel=Auto Actions
jervis.autoAction.sections=actions,skills

# Automated actions that are not directly based on skills
jervis.autoAction.actions.label=Automated Actions

jervis.autoAction.actions.doNotRerollSuccessfulActions.label=Do not reroll successful actions
jervis.autoAction.actions.doNotRerollSuccessfulActions.description=Accept D6 rolls that are a success (Will assume Diving Tackle is used if applicable)
jervis.autoAction.actions.doNotRerollSuccessfulActions.value=true

jervis.autoAction.actions.selectKickingPlayer.label=Select kicking player
jervis.autoAction.actions.selectKickingPlayer.description=Will prioritize players with Kick
jervis.autoAction.actions.selectKickingPlayer.value=true

jervis.autoAction.actions.endPlayerActionIfOnlyOption.label=End player action
jervis.autoAction.actions.endPlayerActionIfOnlyOption.description="Ends the player's activation when it is the only option"
jervis.autoAction.actions.endPlayerActionIfOnlyOption.value=true

jervis.autoAction.actions.selectBlockTypeIfOneOption.label=Select Block type
jervis.autoAction.actions.selectBlockTypeIfOneOption.description=Selects the available Block type if there is only one option
jervis.autoAction.actions.selectBlockTypeIfOneOption.value=true

jervis.autoAction.actions.pushPlayerIntoCrowd.label=Push player into the crowd
jervis.autoAction.actions.pushPlayerIntoCrowd.description=Push an opponent into the crowd if possible
jervis.autoAction.actions.pushPlayerIntoCrowd.value=true

jervis.autoAction.actions.acceptTeamCaptainResult.label=Team Captain
jervis.autoAction.actions.acceptTeamCaptainResult.description=Ask to use Team Re-rolls on failed Team Captain rolls.
jervis.autoAction.actions.acceptTeamCaptainResult.value=false

# Automated actions for when to automatically apply skills
jervis.autoAction.skills.label=Automated Skill Usage

jervis.autoAction.skills.alwaysUseBigHand.label=Big Hand
jervis.autoAction.skills.alwaysUseBigHand.description=Improve Pickup and Secure the Ball
jervis.autoAction.skills.alwaysUseBigHand.value=true

jervis.autoAction.skills.useBullseye.label=Bullseye
jervis.autoAction.skills.useBullseye.description=Use Bullseye when using Throw Team-mate (unless at max range)
jervis.autoAction.skills.useBullseye.value=true

jervis.autoAction.skills.useCatchSkillReroll.label=Catch
jervis.autoAction.skills.useCatchSkillReroll.description=Reroll failed catch attempts
jervis.autoAction.skills.useCatchSkillReroll.value=true

jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.label=Dirty Player (Armour Roll)
jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.description=Use on Armour Roll if needed to break armour
jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.value=true

jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.label=Dirty Player (Injury Roll)
jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.description=Use on Injury Roll if possible
jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.value=true

jervis.autoAction.skills.alwaysUseDivingCatchOnTarget.label=Diving Catch (On Target)
jervis.autoAction.skills.alwaysUseDivingCatchOnTarget.description=Use to catch when ball is on target square
jervis.autoAction.skills.alwaysUseDivingCatchOnTarget.value=true

jervis.autoAction.skills.alwaysUseDivingCatchOnAdjacent.label=Diving Catch (Adjacent Square)
jervis.autoAction.skills.alwaysUseDivingCatchOnAdjacent.description=Include in pool of players available to catch the ball
jervis.autoAction.skills.alwaysUseDivingCatchOnAdjacent.value=true

jervis.autoAction.skills.ignoreDivingTackleIfNoEffect.label=Diving Tackle (No Effect)
jervis.autoAction.skills.ignoreDivingTackleIfNoEffect.description=Do not use Diving Tackle to go Prone if it has no effect
jervis.autoAction.skills.ignoreDivingTackleIfNoEffect.value=true

jervis.autoAction.skills.alwaysUseEyeGouge.label=Eye Gouge
jervis.autoAction.skills.alwaysUseEyeGouge.description=Use when pushing back players
jervis.autoAction.skills.alwaysUseEyeGouge.value=true

jervis.autoAction.skills.alwaysUseGrab.label=Grab
jervis.autoAction.skills.alwaysUseGrab.description=Use to control opponent pushback direction
jervis.autoAction.skills.alwaysUseGrab.value=false

jervis.autoAction.skills.alwaysUseLeapModifier.label=Leap (Modifier)
jervis.autoAction.skills.alwaysUseLeapModifier.description=Apply modifier when leaping over opponents
jervis.autoAction.skills.alwaysUseLeapModifier.value=true

jervis.autoAction.skills.useLethalFlightOnArmourRoll.label=Lethal Flight (Armour Roll)
jervis.autoAction.skills.useLethalFlightOnArmourRoll.description=Use on Armour Roll if needed to break armour
jervis.autoAction.skills.useLethalFlightOnArmourRoll.value=true

jervis.autoAction.skills.useLethalFlightOnInjuryRoll.label=Lethal Flight (Injury Roll)
jervis.autoAction.skills.useLethalFlightOnInjuryRoll.description=Use on Injury Roll if possible
jervis.autoAction.skills.useLethalFlightOnInjuryRoll.value=true

jervis.autoAction.skills.acceptLonerResult.label=Loner
jervis.autoAction.skills.acceptLonerResult.description=Ask to use Team Re-rolls on failed Loner rolls.
jervis.autoAction.skills.acceptLonerResult.value=false

jervis.autoAction.skills.useMightyBlowOnArmourRoll.label=Mighty Blow (Armour Roll)
jervis.autoAction.skills.useMightyBlowOnArmourRoll.description=Use on Armour Roll if needed to break armour
jervis.autoAction.skills.useMightyBlowOnArmourRoll.value=true

jervis.autoAction.skills.useMightyBlowOnInjuryRoll.label=Mighty Blow (Injury Roll)
jervis.autoAction.skills.useMightyBlowOnInjuryRoll.description=Use on Injury Roll if possible
jervis.autoAction.skills.useMightyBlowOnInjuryRoll.value=true

jervis.autoAction.skills.usePassSkillReroll.label=Pass
jervis.autoAction.skills.usePassSkillReroll.description=Reroll failed pass attempts
jervis.autoAction.skills.usePassSkillReroll.value=true

jervis.autoAction.skills.acceptProResult.label=Pro
jervis.autoAction.skills.acceptProResult.description=Ask to use Team Re-rolls on failed Pro rolls.
jervis.autoAction.skills.acceptProResult.value=false

jervis.autoAction.skills.alwaysUseSafePairOfHands.label=Safe Pair of Hands
jervis.autoAction.skills.alwaysUseSafePairOfHands.description=Place ball before being Knocked Down, Fall Over or Placed Prone
jervis.autoAction.skills.alwaysUseSafePairOfHands.value=true

jervis.autoAction.skills.alwaysUseSafePass.label=Safe Pass
jervis.autoAction.skills.alwaysUseSafePass.description=Prevent fumbles on pass attempts
jervis.autoAction.skills.alwaysUseSafePass.value=true

jervis.autoAction.skills.alwaysUseSidestep.label=Sidestep
jervis.autoAction.skills.alwaysUseSidestep.description=Uses to control pushback direction
jervis.autoAction.skills.alwaysUseSidestep.value=true

jervis.autoAction.skills.alwaysUseSneakyGit.label=Sneaky Git
jervis.autoAction.skills.alwaysUseSneakyGit.description=Uses Sneaky Git to avoid being sent off
jervis.autoAction.skills.alwaysUseSneakyGit.value=true

jervis.autoAction.skills.alwaysUseStandFirm.label=Stand Firm
jervis.autoAction.skills.alwaysUseStandFirm.description=Prevent being pushed back during block
jervis.autoAction.skills.alwaysUseStandFirm.value=false

jervis.autoAction.skills.alwaysSteadyFooting.label=Steady Footing
jervis.autoAction.skills.alwaysSteadyFooting.description=Prevent being Knocked Down or Fall Over
jervis.autoAction.skills.alwaysSteadyFooting.value=true

jervis.autoAction.skills.alwaysStripBall.label=Strip Ball
jervis.autoAction.skills.alwaysStripBall.description=Use to knock ball loose after following up in a Block
jervis.autoAction.skills.alwaysStripBall.value=false

jervis.autoAction.skills.alwaysStrongArm.label=Strong Arm
jervis.autoAction.skills.alwaysStrongArm.description=Improve accuracy when throwing players
jervis.autoAction.skills.alwaysStrongArm.value=true

jervis.autoAction.skills.useSureHandReroll.label=Sure Hand (Pickup)
jervis.autoAction.skills.useSureHandReroll.description=Reroll failed Pickup attempts
jervis.autoAction.skills.useSureHandReroll.value=true

jervis.autoAction.skills.useSureHandPushback.label=Sure Hand (Pushed Back)
jervis.autoAction.skills.useSureHandPushback.description=Prevent Strip Ball
jervis.autoAction.skills.useSureHandPushback.value=true

jervis.autoAction.skills.alwaysUseTackleInStumble.label=Tackle (Stumble)
jervis.autoAction.skills.alwaysUseTackleInStumble.description="Cancel opponent's Dodge during a Stumble block result"
jervis.autoAction.skills.alwaysUseTackleInStumble.value=true

jervis.autoAction.skills.alwaysUseTackleToPreventDodge.label=Tackle (Dodge Away)
jervis.autoAction.skills.alwaysUseTackleToPreventDodge.description=Prevent opponent from using Dodge when moving away
jervis.autoAction.skills.alwaysUseTackleToPreventDodge.value=true

jervis.autoAction.skills.alwaysUseThickSkull.label=Thick Skull
jervis.autoAction.skills.alwaysUseThickSkull.description=Apply modifier to injury rolls
jervis.autoAction.skills.alwaysUseThickSkull.value=true

jervis.autoAction.skills.alwaysUseVeryLongLegs.label=Very Long Legs
jervis.autoAction.skills.alwaysUseVeryLongLegs.description=Use modifier when during a Jump or Leap
jervis.autoAction.skills.alwaysUseVeryLongLegs.value=true

# -- GAME_MENU: UI Settings
# If enabled will show the dogout behind players, otherwise there will only be the game background
jervis.ui.sectionLabel=UI Settings

jervis.ui.showDogoutBackground.label=Dogout Background
jervis.ui.showDogoutBackground.description=Shows the dugout background image behind players in the dugout area
jervis.ui.showDogoutBackground.value=true

# If enabled, the current pitch weather is used as the entire game background.
# This might also impact the color of the log views.
# If disabled, the "nice" weather effect is used
jervis.ui.usePitchWeatherAsGameBackground.label=Pitch weather as game background
jervis.ui.usePitchWeatherAsGameBackground.description=Uses the current pitch weather conditions as the game background
jervis.ui.usePitchWeatherAsGameBackground.value=false

jervis.ui.showMouseOverEffectOnSquare.label=Highlight current square
jervis.ui.showMouseOverEffectOnSquare.description=Highlight field square when the mouse pointer is over it
jervis.ui.showMouseOverEffectOnSquare.value=true

jervis.ui.hideJumpIfLeapIsAvailable.label=Hide Jump if Leap is available
jervis.ui.hideJumpIfLeapIsAvailable.description=Hide the Jump action when the Leap action is available
jervis.ui.hideJumpIfLeapIsAvailable.value=true