# These settings will be applied when the Client is initialized
# TODO Figure out how to handle client version updates and new settings are applied

# FUMBBL values
fumbbl.oauth.token=
fumbbl.client.name=
fumbbl.client.id=
fumbbl.client.secret=

# Settings to save between creating new Standalone games
jervis.default.client.coach.name=
jervis.default.host.coach.name=

# The following sections follow a certain format in order to auto-generate code
# that can be used to generate the in-game menu. Each section must start with
# a special directive entry: <xx>.<yy>.label=<header>.
# This will generate a top-level menu which will contain all entries with the
# same <xx>.<yy> prefix.
# Only boolean values are supported right now.

# -- GAME_MENU: Automatic Actions --
# Actions that will automatically be selected by the Game Client before the
# Coach is presented with the option
jervis.autoAction.sectionLabel=Auto Actions
jervis.autoAction.sections=actions,skills

# Automated actions that are not directly based on skills
jervis.autoAction.actions.label=Automated Actions

jervis.autoAction.actions.doNotRerollSuccessfulActions.label=Do not reroll successful actions
jervis.autoAction.actions.doNotRerollSuccessfulActions.description=Accept D6 rolls that are a success
jervis.autoAction.actions.doNotRerollSuccessfulActions.value=true

jervis.autoAction.actions.selectKickingPlayer.label=Select kicking player
jervis.autoAction.actions.selectKickingPlayer.description=Will prioritize players with Kick
jervis.autoAction.actions.selectKickingPlayer.value=true

jervis.autoAction.actions.endPlayerActionIfOnlyOption.label=End player action
jervis.autoAction.actions.endPlayerActionIfOnlyOption.description="Ends the player's activation when it is the only option"
jervis.autoAction.actions.endPlayerActionIfOnlyOption.value=true

jervis.autoAction.actions.selectBlockTypeIfOneOption.label=Select Block type
jervis.autoAction.actions.selectBlockTypeIfOneOption.description=Selects the available Block type if there is only one option
jervis.autoAction.actions.selectBlockTypeIfOneOption.value=true

jervis.autoAction.actions.pushPlayerIntoCrowd.label=Push player into the crowd
jervis.autoAction.actions.pushPlayerIntoCrowd.description=Push an opponent into the crowd if possible
jervis.autoAction.actions.pushPlayerIntoCrowd.value=true

# Automated actions for when to automatically apply skills
jervis.autoAction.skills.label=Automated Skill Usage

jervis.autoAction.skills.alwaysUseBigHand.label=Big Hand
jervis.autoAction.skills.alwaysUseBigHand.description=Use to Pickup and Secure the Ball
jervis.autoAction.skills.alwaysUseBigHand.value=true

jervis.autoAction.skills.useCatchSkillReroll.label=Catch
jervis.autoAction.skills.useCatchSkillReroll.description=Use to reroll failed catch attempts
jervis.autoAction.skills.useCatchSkillReroll.value=true

jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.label=Dirty Player (Armour Roll)
jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.description=Use on Armour Roll if needed to break the armour
jervis.autoAction.skills.useDirtyPlayerOnArmourRoll.value=true

jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.label=Dirty Player (Injury Roll)
jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.description=Use on Injury Roll if possible
jervis.autoAction.skills.useDirtyPlayerOnInjuryRoll.value=true

jervis.autoAction.skills.alwaysUseGrab.label=Grab
jervis.autoAction.skills.alwaysUseGrab.description=Use to control opponent pushback direction
jervis.autoAction.skills.alwaysUseGrab.value=false

jervis.autoAction.skills.alwaysUseLeapModifier.label=Leap (Modifier)
jervis.autoAction.skills.alwaysUseLeapModifier.description=Apply modifier when leaping over opponents
jervis.autoAction.skills.alwaysUseLeapModifier.value=true

jervis.autoAction.skills.usePassSkillReroll.label=Pass
jervis.autoAction.skills.usePassSkillReroll.description=Use to reroll failed pass attempts
jervis.autoAction.skills.usePassSkillReroll.value=true

jervis.autoAction.skills.alwaysUseSafePass.label=Safe Pass
jervis.autoAction.skills.alwaysUseSafePass.description=Use to prevent fumbles on pass attempts
jervis.autoAction.skills.alwaysUseSafePass.value=true

jervis.autoAction.skills.alwaysUseSidestep.label=Sidestep
jervis.autoAction.skills.alwaysUseSidestep.description=Uses to control pushback direction
jervis.autoAction.skills.alwaysUseSidestep.value=true

jervis.autoAction.skills.alwaysUseStandFirm.label=Stand Firm
jervis.autoAction.skills.alwaysUseStandFirm.description=Use to prevent being pushed back during block
jervis.autoAction.skills.alwaysUseStandFirm.value=false

jervis.autoAction.skills.useSureHandReroll.label=Sure Hand
jervis.autoAction.skills.useSureHandReroll.description=Use to reroll failed Pickup attempts
jervis.autoAction.skills.useSureHandReroll.value=true

jervis.autoAction.skills.alwaysUseTackleInStumble.label=Tackle (Stumble)
jervis.autoAction.skills.alwaysUseTackleInStumble.description="Use to cancel opponent's Dodge during a Stumble block result"
jervis.autoAction.skills.alwaysUseTackleInStumble.value=true

jervis.autoAction.skills.alwaysUseTackleToPreventDodge.label=Tackle (Dodge Away)
jervis.autoAction.skills.alwaysUseTackleToPreventDodge.description=Use to prevent opponent from using Dodge when moving away
jervis.autoAction.skills.alwaysUseTackleToPreventDodge.value=true

jervis.autoAction.skills.alwaysUseThickSkull.label=Thick Skull
jervis.autoAction.skills.alwaysUseThickSkull.description=Apply modifier to injury rolls
jervis.autoAction.skills.alwaysUseThickSkull.value=true

jervis.autoAction.skills.alwaysUseVeryLongLegs.label=Very Long Legs
jervis.autoAction.skills.alwaysUseVeryLongLegs.description=Use modifier when during a Jump or Leap
jervis.autoAction.skills.alwaysUseVeryLongLegs.value=true

# -- GAME_MENU: UI Settings
# If enabled will show the dogout behind players, otherwise there will only be the game background
jervis.ui.sectionLabel=UI Settings

jervis.ui.showDogoutBackground.label=Dogout Background
jervis.ui.showDogoutBackground.description=Shows the dugout background image behind players in the dugout area
jervis.ui.showDogoutBackground.value=true

# If enabled, the current pitch weather is used as the entire game background.
# This might also impact the color of the log views.
# If disabled, the "nice" weather effect is used
jervis.ui.usePitchWeatherAsGameBackground.label=Pitch weather as game background
jervis.ui.usePitchWeatherAsGameBackground.description=Uses the current pitch weather conditions as the game background
jervis.ui.usePitchWeatherAsGameBackground.value=false

jervis.ui.showMouseOverEffectOnSquare.label=Highlight current square
jervis.ui.showMouseOverEffectOnSquare.description=Highlight field square when the mouse pointer is over it
jervis.ui.showMouseOverEffectOnSquare.value=true

jervis.ui.hideJumpIfLeapIsAvailable.label=Hide Jump if Leap is available
jervis.ui.hideJumpIfLeapIsAvailable.description=Hide the Jump action when the Leap action is available
jervis.ui.hideJumpIfLeapIsAvailable.value=true